# Generated by Django 4.2.4 on 2023-11-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_roles_remove_profileuser_user_alter_carrito_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='plataforma',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
