# Generated by Django 4.2.4 on 2023-11-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_producto_plataforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='plataforma',
            field=models.CharField(max_length=50),
        ),
    ]
