# Generated by Django 4.2.4 on 2023-11-21 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_remove_order_adress_remove_order_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.order'),
        ),
    ]
