# Generated by Django 4.2.4 on 2023-11-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_itemcart_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
